name: Serialize as CIDOC

on:
  workflow_dispatch

jobs:
  to_cidoc:
    name: Serialize as CIDOC
    runs-on: ubuntu-latest
    env:
      OWNCLOUD_USER: ${{ secrets.OWNCLOUD_USER }}
      OWNCLOUD_PW: ${{ secrets.OWNCLOUD_PW }}
      RDF_FILE_NAME: wmp1.nt
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: install python things
      run: pip install -r requirements.txt
    - name: Fetch the data
      run: ./fetch_data.sh
    - name: create cidoc data set
      run: ./cidoc/build_graph.sh
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RDF_FILE_NAME }}
        path: datasets/${{ env.RDF_FILE_NAME }}
    - name: validate cidoc data set
      run: ./cidoc/validate.sh
    - uses: actions/upload-artifact@v4
      with:
        name: validation_report.txt
        path: datasets/validation_report.txt
    
    
